"""Constraints the model must declare, not only the database must hold.

A constraint that exists in a migration but not on the model is invisible to
`alembic revision --autogenerate`, which compares the model against the
database and therefore reports the live constraint as something to drop. The
next person to accept an autogenerated revision removes it, and nothing fails.

That is not hypothetical here. `uq_backtest_window_one_holdout_per_run` lived
only in a migration for three revisions; two of those revisions recorded
autogenerate proposing to drop it and wrote the proposal off as a partial-index
comparison limitation. It was not a limitation. The index was genuinely absent
from the model, and the run that dropped it would have removed the guarantee
that a backtest run has one holdout, silently, in a diff that looked like
tidying.

An integration test that inserts a duplicate row proves the database has the
constraint today. It says nothing about whether the model still asks for it.
These do.
"""

from __future__ import annotations

from sqlalchemy import Index, UniqueConstraint

from app.models.backtest import BacktestWindow
from app.models.instrument import Instrument


def uniques(table: object) -> set[str]:
    return {
        c.name
        for c in table.__table__.constraints  # type: ignore[attr-defined]
        if isinstance(c, UniqueConstraint) and c.name
    }


def indexes(table: object) -> dict[str, Index]:
    return {i.name: i for i in table.__table__.indexes if i.name}  # type: ignore[attr-defined]


class TestAnchorsAreUniqueOnTheModel:
    """One external identifier, one company.

    `upsert_instrument` finds a company by its anchor and takes the first row
    back. Two rows sharing an anchor make that lookup return whichever the
    planner ordered first, and the two then take turns owning one symbol
    history.
    """

    def test_the_dart_corp_code_is_declared_unique(self) -> None:
        assert "uq_instrument_kr_corp_code" in uniques(Instrument)

    def test_the_sec_cik_is_declared_unique(self) -> None:
        assert "uq_instrument_us_cik" in uniques(Instrument)

    def test_each_covers_exactly_its_own_column(self) -> None:
        by_name = {
            c.name: c
            for c in Instrument.__table__.constraints
            if isinstance(c, UniqueConstraint) and c.name
        }

        assert [c.name for c in by_name["uq_instrument_kr_corp_code"].columns] == ["kr_corp_code"]
        assert [c.name for c in by_name["uq_instrument_us_cik"].columns] == ["us_cik"]


class TestOneHoldoutPerRunIsDeclared:
    def test_the_partial_index_is_on_the_model(self) -> None:
        assert "uq_backtest_window_one_holdout_per_run" in indexes(BacktestWindow)

    def test_it_is_unique_and_partial(self) -> None:
        """Unique over every run, but only among holdout rows.

        Dropping the predicate would forbid a run from having more than one
        window of any kind, which is what a walk-forward run is made of.
        """
        index = indexes(BacktestWindow)["uq_backtest_window_one_holdout_per_run"]

        assert index.unique is True
        assert [c.name for c in index.columns] == ["run_id"]
        where = index.dialect_options["postgresql"].get("where")
        assert where is not None
        assert "HOLDOUT" in str(where)
