"""initial schema: instrument identity, market data, portfolio, signals, collector runs

Revision ID: 037af55ddd92
Revises:
Create Date: 2026-09-19 13:58:41.575052
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "037af55ddd92"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collector_run",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=48), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "SUCCESS",
                "PARTIAL",
                "FAILED",
                "SKIPPED",
                name="collector_status",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("items_read", sa.Integer(), nullable=False),
        sa.Column("items_saved", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("detail", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collector_run")),
    )
    op.create_index(
        "ix_collector_run_source_started", "collector_run", ["source", "started_at"], unique=False
    )
    op.create_index(
        "ix_collector_run_source_status",
        "collector_run",
        ["source", "status", "finished_at"],
        unique=False,
    )
    op.create_table(
        "fx_rate",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("base", sa.String(length=3), nullable=False),
        sa.Column("quote", sa.String(length=3), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fx_rate")),
        sa.UniqueConstraint("base", "quote", "rate_date", name="uq_fx_rate_base_quote_date"),
    )
    op.create_index("ix_fx_rate_pair_date", "fx_rate", ["base", "quote", "rate_date"], unique=False)
    op.create_table(
        "instrument",
        sa.Column("instrument_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "market",
            sa.Enum("KR", "US", name="market", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("listed_at", sa.Date(), nullable=True),
        sa.Column("delisted_at", sa.Date(), nullable=True),
        sa.Column("us_cik", sa.String(length=10), nullable=True),
        sa.Column("kr_corp_code", sa.String(length=8), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("instrument_id", name=op.f("pk_instrument")),
        sa.UniqueConstraint("kr_corp_code", name="uq_instrument_kr_corp_code"),
        sa.UniqueConstraint("us_cik", name="uq_instrument_us_cik"),
    )
    op.create_index("ix_instrument_market_name", "instrument", ["market", "name"], unique=False)
    op.create_table(
        "portfolio_snapshot",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("total_value_krw", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("invested_krw", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("cash_krw", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("pnl_krw", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("pnl_local_krw_equiv", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("pnl_fx_krw", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_snapshot")),
        sa.UniqueConstraint("snapshot_date", name="uq_portfolio_snapshot_date"),
    )
    op.create_index(
        "ix_portfolio_snapshot_date", "portfolio_snapshot", ["snapshot_date"], unique=False
    )
    op.create_table(
        "strategy_config",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("technical_params", sa.JSON(), nullable=False),
        sa.Column("normalization_method", sa.String(length=24), nullable=False),
        sa.Column("weights", sa.JSON(), nullable=False),
        sa.Column("signal_thresholds", sa.JSON(), nullable=False),
        sa.Column("freshness_policy", sa.JSON(), nullable=False),
        sa.Column(
            "missing_factor_policy",
            sa.Enum(
                "ABSTAIN",
                "ZERO",
                "RENORMALIZE",
                name="strategy_missing_policy",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("required_factors", sa.JSON(), nullable=False),
        sa.Column("sentiment_scorer", sa.JSON(), nullable=False),
        sa.Column("fundamental_revision_policy", sa.String(length=24), nullable=False),
        sa.Column("universe_definition", sa.JSON(), nullable=False),
        sa.Column("execution_model", sa.String(length=24), nullable=False),
        sa.Column("commission_model", sa.JSON(), nullable=False),
        sa.Column("slippage_model", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_config")),
        sa.UniqueConstraint("version", name=op.f("uq_strategy_config_version")),
    )
    op.create_table(
        "candle",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "interval",
            sa.Enum("MIN_1", "DAY_1", name="candle_interval", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("volume", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
            name=op.f("fk_candle_instrument_id_instrument"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candle")),
        sa.UniqueConstraint(
            "instrument_id", "interval", "ts", name="uq_candle_instrument_interval_ts"
        ),
    )
    op.create_index("ix_candle_ingested", "candle", ["ingested_at"], unique=False)
    op.create_index("ix_candle_lookup", "candle", ["instrument_id", "interval", "ts"], unique=False)
    op.create_table(
        "corporate_action",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "DIVIDEND",
                "SPLIT",
                "REVERSE_SPLIT",
                "BONUS_ISSUE",
                "MERGER",
                name="corporate_action_type",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("announced_at", sa.Date(), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ratio", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("amount", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
            name=op.f("fk_corporate_action_instrument_id_instrument"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corporate_action")),
        sa.UniqueConstraint(
            "instrument_id",
            "action_type",
            "ex_date",
            name="uq_corporate_action_instrument_type_exdate",
        ),
    )
    op.create_index(
        "ix_corporate_action_lookup", "corporate_action", ["instrument_id", "ex_date"], unique=False
    )
    op.create_table(
        "holding",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("avg_price", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("avg_fx_rate", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
            name=op.f("fk_holding_instrument_id_instrument"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holding")),
        sa.UniqueConstraint("instrument_id", name="uq_holding_instrument"),
    )
    op.create_index("ix_holding_instrument", "holding", ["instrument_id"], unique=False)
    op.create_table(
        "signal",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("data_asof", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decision_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("earliest_execution_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "BUY_INTEREST",
                "WATCH",
                "CAUTION",
                "ABSTAINED",
                name="signal_action",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "policy",
            sa.Enum(
                "ABSTAIN",
                "ZERO",
                "RENORMALIZE",
                name="missing_factor_policy",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("abstained_reason", sa.String(length=300), nullable=True),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("strategy_version", sa.String(length=32), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
            name=op.f("fk_signal_instrument_id_instrument"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal")),
    )
    op.create_index("ix_signal_decision_at", "signal", ["decision_at"], unique=False)
    op.create_index(
        "ix_signal_instrument_decision", "signal", ["instrument_id", "decision_at"], unique=False
    )
    op.create_table(
        "symbol_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
            name=op.f("fk_symbol_history_instrument_id_instrument"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_symbol_history")),
    )
    op.create_index(
        "ix_symbol_history_instrument", "symbol_history", ["instrument_id"], unique=False
    )
    op.create_index(
        "ix_symbol_history_symbol_window",
        "symbol_history",
        ["symbol", "valid_from", "valid_to"],
        unique=False,
    )
    op.create_table(
        "transaction",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "side",
            sa.Enum("BUY", "SELL", name="transaction_side", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("price", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("fx_rate", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("fee", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("tax", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
            name=op.f("fk_transaction_instrument_id_instrument"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transaction")),
    )
    op.create_index(
        "ix_transaction_instrument_time",
        "transaction",
        ["instrument_id", "executed_at"],
        unique=False,
    )
    op.create_table(
        "signal_factor",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("signal_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "engine",
            sa.Enum(
                "TECHNICAL",
                "FUNDAMENTAL",
                "SENTIMENT",
                "PORTFOLIO",
                name="factor_engine",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("requested_weight", sa.Float(), nullable=False),
        sa.Column("effective_weight", sa.Float(), nullable=False),
        sa.Column("contribution", sa.Float(), nullable=False),
        sa.Column(
            "availability",
            sa.Enum(
                "AVAILABLE", "UNAVAILABLE", name="factor_availability", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("availability_reason", sa.String(length=300), nullable=True),
        sa.Column("source_asof", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_age", sa.Interval(), nullable=True),
        sa.Column(
            "freshness_status",
            sa.Enum(
                "FRESH", "STALE", "MISSING", name="freshness_status", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signal.id"],
            name=op.f("fk_signal_factor_signal_id_signal"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_factor")),
    )
    op.create_index("ix_signal_factor_signal", "signal_factor", ["signal_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_signal_factor_signal", table_name="signal_factor")
    op.drop_table("signal_factor")
    op.drop_index("ix_transaction_instrument_time", table_name="transaction")
    op.drop_table("transaction")
    op.drop_index("ix_symbol_history_symbol_window", table_name="symbol_history")
    op.drop_index("ix_symbol_history_instrument", table_name="symbol_history")
    op.drop_table("symbol_history")
    op.drop_index("ix_signal_instrument_decision", table_name="signal")
    op.drop_index("ix_signal_decision_at", table_name="signal")
    op.drop_table("signal")
    op.drop_index("ix_holding_instrument", table_name="holding")
    op.drop_table("holding")
    op.drop_index("ix_corporate_action_lookup", table_name="corporate_action")
    op.drop_table("corporate_action")
    op.drop_index("ix_candle_lookup", table_name="candle")
    op.drop_index("ix_candle_ingested", table_name="candle")
    op.drop_table("candle")
    op.drop_table("strategy_config")
    op.drop_index("ix_portfolio_snapshot_date", table_name="portfolio_snapshot")
    op.drop_table("portfolio_snapshot")
    op.drop_index("ix_instrument_market_name", table_name="instrument")
    op.drop_table("instrument")
    op.drop_index("ix_fx_rate_pair_date", table_name="fx_rate")
    op.drop_table("fx_rate")
    op.drop_index("ix_collector_run_source_status", table_name="collector_run")
    op.drop_index("ix_collector_run_source_started", table_name="collector_run")
    op.drop_table("collector_run")
    # ### end Alembic commands ###
