"""LLM 판정의 출처, 기사 해석 결과, LLM 호출 원장

세 가지를 더한다.

- `news_relevance_decision`에 `model`, `prompt_version`, `rationale`. 규칙 판정은
  `rule_version`으로 재현되지만 LLM 판정은 어떤 모델이 어떤 프롬프트로 내렸는지가 있어야
  재현된다. 규칙 판정에는 비어 있다.
- `news_sentiment`: 기사 하나가 회사 하나에 대해 무엇을 말하는지, 모델 하나가 한 번 읽은
  결과. (기사, 회사, 모델, 프롬프트 버전)이 키이고 덮어쓰지 않는다. 방향(-1~+1), 이벤트
  종류, 강도, 신뢰도, 근거 문장을 담는다. 아직 어떤 점수에도 들어가지 않는다.
- `llm_call`: 모든 LLM 호출 한 건당 한 행. 목적, 모델, 토큰, API였다면 냈을 금액, 호출
  직후 구독의 5시간·7일 사용률. 쿼터 원장은 호출 수만 세므로 이것들을 담지 못한다.

Revision ID: 2f3055a5ef2b
Revises: 91a111bcedb5
Create Date: 2026-09-23
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "2f3055a5ef2b"
down_revision: str | None = "91a111bcedb5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_call",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "called_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.Integer(), nullable=False),
        sa.Column("items", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("notional_cost_usd", sa.Float(), nullable=True),
        sa.Column("five_hour_utilization", sa.Float(), nullable=True),
        sa.Column("seven_day_utilization", sa.Float(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_call")),
    )
    op.create_index("ix_llm_call_purpose_time", "llm_call", ["purpose", "called_at"], unique=False)
    op.create_table(
        "news_sentiment",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("news_item_id", sa.BigInteger(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.Integer(), nullable=False),
        sa.Column("sentiment", sa.Float(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "EARNINGS",
                "GUIDANCE",
                "ORDER_CONTRACT",
                "PRODUCT",
                "SHAREHOLDER_RETURN",
                "CAPITAL_RAISE",
                "MERGER_ACQUISITION",
                "LEGAL_REGULATORY",
                "MANAGEMENT",
                "ANALYST_RATING",
                "PRICE_MOVE",
                "INDUSTRY",
                "OTHER",
                name="sentiment_event",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("intensity", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
            name=op.f("fk_news_sentiment_instrument_id_instrument"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["news_item_id"],
            ["news_item.id"],
            name=op.f("fk_news_sentiment_news_item_id_news_item"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news_sentiment")),
        sa.UniqueConstraint(
            "news_item_id",
            "instrument_id",
            "model",
            "prompt_version",
            name="uq_news_sentiment_reading",
        ),
    )
    op.create_index(
        "ix_news_sentiment_instrument_created",
        "news_sentiment",
        ["instrument_id", "created_at"],
        unique=False,
    )
    op.add_column(
        "news_relevance_decision", sa.Column("model", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "news_relevance_decision", sa.Column("prompt_version", sa.Integer(), nullable=True)
    )
    op.add_column("news_relevance_decision", sa.Column("rationale", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_relevance_decision", "rationale")
    op.drop_column("news_relevance_decision", "prompt_version")
    op.drop_column("news_relevance_decision", "model")
    op.drop_index("ix_news_sentiment_instrument_created", table_name="news_sentiment")
    op.drop_table("news_sentiment")
    op.drop_index("ix_llm_call_purpose_time", table_name="llm_call")
    op.drop_table("llm_call")
    # ### end Alembic commands ###
