"""filing register: prove whether a report existed, not just whether we tagged it

Revision ID: 5489f8841308
Revises: a675f09d5f60
Create Date: 2026-09-19 17:07:54.740518
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "5489f8841308"
down_revision: str | None = "a675f09d5f60"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filing",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("form", sa.String(length=24), nullable=False),
        sa.Column("filed_at", sa.Date(), nullable=False),
        sa.Column("period_of_report", sa.Date(), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accession", sa.String(length=32), nullable=False),
        sa.Column(
            "source",
            sa.Enum("SEC", "DART", "YFINANCE", name="filing_source", native_enum=False, length=12),
            nullable=False,
        ),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
            name=op.f("fk_filing_instrument_id_instrument"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_filing")),
        sa.UniqueConstraint("instrument_id", "accession", name="uq_filing_instrument_accession"),
    )
    op.create_index(
        "ix_filing_available", "filing", ["instrument_id", "available_at"], unique=False
    )
    op.create_index(
        "ix_filing_lookup",
        "filing",
        ["instrument_id", "form", "period_of_report", "filed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_filing_lookup", table_name="filing")
    op.drop_index("ix_filing_available", table_name="filing")
    op.drop_table("filing")
    # ### end Alembic commands ###
