"""판단 뒤에 일어난 일을 기록한다 (Phase 4-8 포워드 테스트)

뉴스에는 백테스트할 과거가 없다. 오버레이, 관련성 규칙, 후보 순위가 쓸모 있는지는 그것이
말한 것과 그 뒤 시장이 한 일을 적어 두는 수밖에 없다. 이 세 테이블이 그 기록이다.

- `signal_outcome`: 신호의 수익률. 진입은 백테스트와 같은 규칙으로 다음 세션 시가
  (`earliest_execution_at`), 청산은 진입 세션을 1로 세어 1·5·20번째 세션의 종가.
- `candidate_snapshot`: 그날의 발굴 목록을 그때 모습 그대로.
- `candidate_outcome`: 목록에 오른 후보의 수익률. 목록을 뽑은 뒤 첫 시가에 진입.

결과는 가격이 생긴 뒤에 덧붙고, 판단 자체는 바꾸지 않는다.

Revision ID: 6502bd53cc5c
Revises: 6e7d510a9a32
Create Date: 2026-09-24
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "6502bd53cc5c"
down_revision: str | None = "6e7d510a9a32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_snapshot",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "taken_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("asof", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("recent_mentions", sa.Integer(), nullable=False),
        sa.Column("baseline_mentions", sa.Integer(), nullable=False),
        sa.Column("recent_days", sa.Float(), nullable=False),
        sa.Column("baseline_days", sa.Float(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("news_freshness", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
            name=op.f("fk_candidate_snapshot_instrument_id_instrument"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_snapshot")),
        sa.UniqueConstraint("asof", "instrument_id", name="uq_candidate_snapshot_asof_instrument"),
    )
    op.create_index("ix_candidate_snapshot_asof", "candidate_snapshot", ["asof"], unique=False)
    op.create_table(
        "candidate_outcome",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("horizon_sessions", sa.Integer(), nullable=False),
        sa.Column("entry_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("exit_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exit_price", sa.Float(), nullable=False),
        sa.Column("return_pct", sa.Float(), nullable=False),
        sa.Column(
            "measured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["candidate_snapshot.id"],
            name=op.f("fk_candidate_outcome_snapshot_id_candidate_snapshot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_outcome")),
        sa.UniqueConstraint("snapshot_id", "horizon_sessions", name="uq_candidate_outcome_horizon"),
    )
    op.create_table(
        "signal_outcome",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("signal_id", sa.BigInteger(), nullable=False),
        sa.Column("horizon_sessions", sa.Integer(), nullable=False),
        sa.Column("entry_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("exit_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exit_price", sa.Float(), nullable=False),
        sa.Column("return_pct", sa.Float(), nullable=False),
        sa.Column(
            "measured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signal.id"],
            name=op.f("fk_signal_outcome_signal_id_signal"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_outcome")),
        sa.UniqueConstraint("signal_id", "horizon_sessions", name="uq_signal_outcome_horizon"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("signal_outcome")
    op.drop_table("candidate_outcome")
    op.drop_index("ix_candidate_snapshot_asof", table_name="candidate_snapshot")
    op.drop_table("candidate_snapshot")
    # ### end Alembic commands ###
