"""신호 옆에 뉴스 이벤트 오버레이를 남긴다 (Phase 4-4)

기본 점수(기술 0.6, 재무 0.4)는 10년 이력으로 검증됐고, 뉴스에는 이력이 없다. 그래서
뉴스는 가중치에 들어가지 않는다. 기사 해석을 사건 단위로 묶고, 반감기로 줄이고, 상한이 있는
점수로 바꿔 신호마다 한 행씩 옆에 남긴다. `total_score`와 `action`은 그대로다. 이 둘을
비교하는 것은 포워드 테스트(4-8)의 몫이다.

Revision ID: 6e7d510a9a32
Revises: 2f3055a5ef2b
Create Date: 2026-09-23
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "6e7d510a9a32"
down_revision: str | None = "2f3055a5ef2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signal_overlay",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("signal_id", sa.BigInteger(), nullable=False),
        sa.Column("asof", sa.DateTime(timezone=True), nullable=False),
        sa.Column("overlay_version", sa.Integer(), nullable=False),
        sa.Column("reading_model", sa.String(length=64), nullable=False),
        sa.Column("reading_prompt_version", sa.Integer(), nullable=False),
        sa.Column("points", sa.Float(), nullable=False),
        sa.Column("raw", sa.Float(), nullable=False),
        sa.Column("events", sa.Integer(), nullable=False),
        sa.Column("readings_used", sa.Integer(), nullable=False),
        sa.Column("unread_articles", sa.Integer(), nullable=False),
        sa.Column(
            "news_freshness",
            sa.Enum(
                "FRESH", "STALE", "MISSING", name="freshness_status", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signal.id"],
            name=op.f("fk_signal_overlay_signal_id_signal"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_overlay")),
        sa.UniqueConstraint("signal_id", name=op.f("uq_signal_overlay_signal_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("signal_overlay")
    # ### end Alembic commands ###
