"""스윕이 종목마다 실제로 읽은 시간 구간을 남긴다

검색은 최신 결과부터 한 페이지 100건을 돌려준다. 조용한 회사는 그 페이지가 워터마크
너머까지 닿아서 `[since, 요청 시각]`을 다 읽는다. 기사가 많은 회사는 페이지가 먼저
끝나서 `[가장 오래된 결과, 요청 시각]`만 읽고, 그보다 오래된 기사는 보지 못한다. 첫 전체
스윕에서 2,648종목 중 273종목이 그랬다. 후보 발굴에서 이 차이를 모르면 대형주가 전부
"이전 언급 0건에서 급증"으로 보였다. 그래서 언급 수는 읽은 시간과 함께 세야 한다.

이 테이블 이전의 스윕은 무엇을 읽었는지 기록이 없으므로 추정해서 채우지 않는다.

`collector`는 누가 스윕했는지다. 통합 테스트는 가짜 transport로 실제 종목 마스터 전체를
스윕하는데, 이 열이 없던 초안에서는 테스트 한 번에 2,648종목의 "읽었다"는 기록이 실제
데이터 옆에 쌓였다(dev DB에서 190,672행). 발굴은 실제 수집기의 기록만 읽는다.

Revision ID: 91a111bcedb5
Revises: fcace2fa47f5
Create Date: 2026-09-23
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "91a111bcedb5"
down_revision: str | None = "fcace2fa47f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "news_sweep_coverage",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "NAVER_NEWS", "THREADS", "REDDIT", name="news_source", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("collector", sa.String(length=32), nullable=False),
        sa.Column("covered_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("covered_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capped", sa.Boolean(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
            name=op.f("fk_news_sweep_coverage_instrument_id_instrument"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_news_sweep_coverage")),
    )
    op.create_index(
        "ix_news_sweep_coverage_instrument_to",
        "news_sweep_coverage",
        ["instrument_id", "covered_to"],
        unique=False,
    )
    op.create_index(
        "ix_news_sweep_coverage_collector",
        "news_sweep_coverage",
        ["collector", "recorded_at"],
        unique=False,
    )
    op.create_index(
        "ix_news_sweep_coverage_recorded", "news_sweep_coverage", ["recorded_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index("ix_news_sweep_coverage_collector", table_name="news_sweep_coverage")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_news_sweep_coverage_recorded", table_name="news_sweep_coverage")
    op.drop_index("ix_news_sweep_coverage_instrument_to", table_name="news_sweep_coverage")
    op.drop_table("news_sweep_coverage")
    # ### end Alembic commands ###
