"""해석에 금융 관련성을 묻고, 규칙 판정을 표본으로 감사한다

- `news_sentiment.material`: 투자자에게 의미가 있는 기사인가. 봉사활동이나 후원 구단의
  경기는 회사 이야기이면서 회사 가치에 관한 뉴스는 아니다. 해석 프롬프트 v2부터 묻고, 그
  이전 해석에는 비어 있다. 오버레이는 의미 없다고 읽힌 해석을 넣지 않는다.
- `rule_audit`: 규칙이 확정한 판정 일부를 모델에게 다시 물은 결과. 판정 자체는 바꾸지
  않는다. 모델도 틀리므로 표본으로 규칙을 덮으면 오류를 다른 오류로 바꿀 뿐이다. 다음 규칙
  버전의 근거로만 쓴다.

Revision ID: 95ba16fb4d49
Revises: dff68b1c75df
Create Date: 2026-09-25
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "95ba16fb4d49"
down_revision: str | None = "dff68b1c75df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rule_audit",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("query_hit_id", sa.BigInteger(), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column(
            "rule_decision",
            sa.Enum(
                "CONFIRMED",
                "PENDING",
                "REJECTED",
                name="news_hit_decision",
                native_enum=False,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("rule_reason", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.Integer(), nullable=False),
        sa.Column("model_verdict", sa.String(length=12), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "audited_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["query_hit_id"],
            ["news_query_hit.id"],
            name=op.f("fk_rule_audit_query_hit_id_news_query_hit"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_audit")),
    )
    op.create_index(
        "ix_rule_audit_rule_version", "rule_audit", ["rule_version", "audited_at"], unique=False
    )
    op.add_column("news_sentiment", sa.Column("material", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_sentiment", "material")
    op.drop_index("ix_rule_audit_rule_version", table_name="rule_audit")
    op.drop_table("rule_audit")
    # ### end Alembic commands ###
