"""backtest runs and their provenance

Two tables so that a backtest result can be checked rather than believed.

`backtest_run` holds the three axes that decide a result — the strategy as
kind + version + params, the code as `git_commit_sha`, and the data as
`data_snapshot_at` — plus the costs that were actually applied, expanded into
numbers. A row recording "the default cost model" would become a different
claim the day the default moved, and every stored run would silently
reinterpret itself.

`backtest_window` holds one row per measurement rather than a run-level
average, because averaging in-sample and out-of-sample figures loses exactly
the comparison a walk-forward exists to make. Its unique constraint on
(run, window_index, sample_type) is also what makes a holdout evaluable once:
a second attempt collides instead of appending a second opinion on the one
period nothing was allowed to iterate against.
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "99c1106358d9"
down_revision: str | None = "b2c7d41e9a03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_run",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("strategy_kind", sa.String(length=64), nullable=False),
        sa.Column("strategy_version", sa.String(length=64), nullable=False),
        sa.Column("strategy_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("strategy_fingerprint", sa.String(length=16), nullable=False),
        sa.Column("fitter_version", sa.String(length=64), nullable=True),
        sa.Column("git_commit_sha", sa.String(length=40), nullable=False),
        sa.Column("git_dirty", sa.Boolean(), nullable=False),
        sa.Column("data_snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "interval",
            sa.Enum("MIN_1", "DAY_1", name="backtest_interval", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("starting_cash", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("commission_bps", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("slippage_bps", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("min_commission", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("execution_model", sa.String(length=16), nullable=False),
        sa.Column("bar_minutes", sa.Integer(), nullable=True),
        sa.Column("train_sessions", sa.Integer(), nullable=False),
        sa.Column("eval_sessions", sa.Integer(), nullable=False),
        sa.Column("anchored", sa.Boolean(), nullable=False),
        sa.Column("holdout_start", sa.Date(), nullable=True),
        sa.Column("holdout_end", sa.Date(), nullable=True),
        sa.Column("require_complete_sessions", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(holdout_start IS NULL) = (holdout_end IS NULL)",
            name=op.f("ck_backtest_run_holdout_both_or_neither"),
        ),
        sa.CheckConstraint(
            "period_end >= period_start", name=op.f("ck_backtest_run_period_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
            name=op.f("fk_backtest_run_instrument_id_instrument"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_run")),
    )
    op.create_index(
        "ix_backtest_run_instrument", "backtest_run", ["instrument_id", "started_at"], unique=False
    )
    op.create_index(
        "ix_backtest_run_strategy", "backtest_run", ["strategy_fingerprint"], unique=False
    )
    op.create_table(
        "backtest_window",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("window_index", sa.Integer(), nullable=False),
        sa.Column(
            "sample_type",
            sa.Enum(
                "IN_SAMPLE",
                "OUT_OF_SAMPLE",
                "HOLDOUT",
                name="backtest_sample_type",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("chosen_kind", sa.String(length=64), nullable=False),
        sa.Column("chosen_version", sa.String(length=64), nullable=False),
        sa.Column("chosen_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("chosen_fingerprint", sa.String(length=16), nullable=False),
        sa.Column("sessions", sa.Integer(), nullable=False),
        sa.Column("observations", sa.Integer(), nullable=False),
        sa.Column("total_return", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("cagr", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("max_drawdown", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("sharpe", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("win_rate", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("profit_factor", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("trades", sa.Integer(), nullable=False),
        sa.Column("abstained", sa.Integer(), nullable=False),
        sa.Column("without_data", sa.Integer(), nullable=False),
        sa.Column("unfilled", sa.Integer(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "period_end >= period_start", name=op.f("ck_backtest_window_window_period_ordered")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["backtest_run.id"],
            name=op.f("fk_backtest_window_run_id_backtest_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_window")),
        sa.UniqueConstraint(
            "run_id", "window_index", "sample_type", name="uq_backtest_window_slot"
        ),
    )
    op.create_index(
        "ix_backtest_window_run", "backtest_window", ["run_id", "sample_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_backtest_window_run", table_name="backtest_window")
    op.drop_table("backtest_window")
    op.drop_index("ix_backtest_run_strategy", table_name="backtest_run")
    op.drop_index("ix_backtest_run_instrument", table_name="backtest_run")
    op.drop_table("backtest_run")
    # ### end Alembic commands ###
