"""사건 공시를 남긴다 (Phase 4-5 개정)

`filing`은 재무제표를 채우는 정기공시다. 이 테이블은 다른 쪽, 무슨 일이 생기면 내야 하는
공시(주요사항보고, 거래소공시)다. 자사주 취득, 공급계약, 유상증자, 합병 같은 사건의 가장
권위 있는 기록이고, 기사 대부분은 이 공시를 옮겨 쓴다. Threads와 Reddit을 쓸 수 없게 되면서
오버레이의 두 번째 사건 원천이 된다.

행은 공시가 있었다는 사실이고 바뀌지 않는다. 어떤 사건인지는 공시 제목을 읽는 버전 있는
규칙(`app.scoring.disclosure_events`)이 정한다. 목록 API는 접수일만 주고 시각을 주지 않으므로
사용 가능 시각은 다음 세션 개장이다.

Revision ID: dff68b1c75df
Revises: 6502bd53cc5c
Create Date: 2026-09-25
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "dff68b1c75df"
down_revision: str | None = "6502bd53cc5c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disclosure",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("rcept_no", sa.String(length=14), nullable=False),
        sa.Column("report_nm", sa.String(length=300), nullable=False),
        sa.Column("pblntf_ty", sa.String(length=2), nullable=False),
        sa.Column("filer", sa.String(length=200), nullable=True),
        sa.Column("filed_on", sa.Date(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
            name=op.f("fk_disclosure_instrument_id_instrument"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disclosure")),
        sa.UniqueConstraint("rcept_no", name=op.f("uq_disclosure_rcept_no")),
    )
    op.create_index(
        "ix_disclosure_instrument_available",
        "disclosure",
        ["instrument_id", "available_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_disclosure_instrument_available", table_name="disclosure")
    op.drop_table("disclosure")
    # ### end Alembic commands ###
