"""candle revisions: drop uniqueness so restated bars append

Revision ID: f5f0cc07229c
Revises: 037af55ddd92
Create Date: 2026-09-19 14:33:01.009549
"""

from collections.abc import Sequence

from alembic import op


revision: str = "f5f0cc07229c"
down_revision: str | None = "037af55ddd92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_candle_instrument_interval_ts"), "candle", type_="unique")
    op.drop_index(op.f("ix_candle_lookup"), table_name="candle")
    op.create_index(
        "ix_candle_lookup",
        "candle",
        ["instrument_id", "interval", "ts", "ingested_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_candle_lookup", table_name="candle")
    op.create_index(
        op.f("ix_candle_lookup"), "candle", ["instrument_id", "interval", "ts"], unique=False
    )
    op.create_unique_constraint(
        op.f("uq_candle_instrument_interval_ts"),
        "candle",
        ["instrument_id", "interval", "ts"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
