"""fundamental: financial facts with every filed revision

Revision ID: f6ab8ef222d1
Revises: ab8e9ea61c1b
Create Date: 2026-09-19 16:46:21.652942
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "f6ab8ef222d1"
down_revision: str | None = "ab8e9ea61c1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fundamental",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("taxonomy", sa.String(length=24), nullable=False),
        sa.Column("concept", sa.String(length=128), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column(
            "fiscal_period",
            sa.Enum(
                "FY",
                "Q1",
                "Q2",
                "Q3",
                "Q4",
                "H1",
                "UNKNOWN",
                name="fiscal_period",
                native_enum=False,
                length=8,
            ),
            nullable=False,
        ),
        sa.Column("form", sa.String(length=24), nullable=False),
        sa.Column("value", sa.Numeric(precision=30, scale=6), nullable=False),
        sa.Column("filed_at", sa.Date(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("accession", sa.String(length=32), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "SEC", "DART", "YFINANCE", name="fundamental_source", native_enum=False, length=12
            ),
            nullable=False,
        ),
        sa.Column("frame", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
            name=op.f("fk_fundamental_instrument_id_instrument"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fundamental")),
        sa.UniqueConstraint(
            "instrument_id",
            "taxonomy",
            "concept",
            "unit",
            "period_start",
            "period_end",
            "form",
            "filed_at",
            "accession",
            name="uq_fundamental_context_filing",
        ),
    )
    op.create_index(
        "ix_fundamental_available", "fundamental", ["instrument_id", "available_at"], unique=False
    )
    op.create_index("ix_fundamental_ingested", "fundamental", ["ingested_at"], unique=False)
    op.create_index(
        "ix_fundamental_pit",
        "fundamental",
        ["instrument_id", "taxonomy", "concept", "unit", "period_end", "filed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_fundamental_pit", table_name="fundamental")
    op.drop_index("ix_fundamental_ingested", table_name="fundamental")
    op.drop_index("ix_fundamental_available", table_name="fundamental")
    op.drop_table("fundamental")
    # ### end Alembic commands ###
