"""뉴스에서 찾은 종목이 언제, 어떤 근거로 추적 대상이 됐는지 남긴다

`instrument.tracked`는 지금 추적 중인지만 말한다. 언제부터인지는 말하지 못하므로,
"09/23 10:00에 이미 추적 중이라 후보가 아니었던 종목"을 물으면 오늘 목록으로 답하게 된다.
승격 행이 그 틈을 막는다. 어떤 시점 뒤에 승격된 종목은 그 시점에는 추적 밖이었다.

README가 경고하는 선택 편향의 감사 기록이기도 하다. 뉴스 급증으로 골라진 종목은 그렇게
고른 숫자를 함께 들고 있고, 나중에 그 종목을 포함한 백테스트가 그 사실을 밝힐 수 있다.

한 번 쓰고 고치지 않는다. `promoted_at`은 데이터베이스가 찍는다.

Revision ID: fcace2fa47f5
Revises: 7d2f4b8e1a36
Create Date: 2026-09-23
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "fcace2fa47f5"
down_revision: str | None = "7d2f4b8e1a36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instrument_promotion",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "promoted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("discovered_asof", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_hours", sa.Integer(), nullable=False),
        sa.Column("baseline_days", sa.Float(), nullable=False),
        sa.Column("recent_mentions", sa.Integer(), nullable=False),
        sa.Column("baseline_mentions", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("news_freshness", sa.String(length=8), nullable=False),
        sa.Column("candle_bars", sa.Integer(), nullable=False),
        sa.Column("fundamental_facts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
            name=op.f("fk_instrument_promotion_instrument_id_instrument"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instrument_promotion")),
    )
    op.create_index(
        "ix_instrument_promotion_instrument",
        "instrument_promotion",
        ["instrument_id", "promoted_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_instrument_promotion_instrument", table_name="instrument_promotion")
    op.drop_table("instrument_promotion")
    # ### end Alembic commands ###
